font_family Monocraft
symbol_map U+002D,U+003D JetBrains Mono Nerd Font
font_size 12

window_margin_width 2

foreground #dddddd
background #090409
background_opacity 0.5

shell fish

map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard
map ctrl+x cut_to_clipboard
