general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 120                                 
    on-timeout = brightnessctl -s set 0%       
    on-resume = brightnessctl -r                 
}

listener {
    timeout = 600                                 
    on-timeout = loginctl lock-session
}

