input-field {
    monitor =
    fade_on_empty = false
    placeholder_text= Input Password
    inner_color=rgba(0, 0, 0, 0)
    font_color=rgba(200, 200, 200, 1.0)
    font_family=JetBrains mono
    size= 300, 70
}

label {
   text = cmd[update:1000] date +"%R"
   position = 0, 130
   font_size = 100
   font_family=JetBrains mono
}
