##############################################
############## HYPRIDLE CONFIG ###############
##############################################

# Lock the pc
general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
}

# Turn off the backlight if inactive for 2 minutes
listener {
    timeout = 120
    on-timeout = brightnessctl -s set 0%
    on-resume = brightnessctl -r
}

# Lock after being inactive for 10 minutes
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}
