[mgr]
show_hidden = true

[opener]
unzip = [
    { run = 'unzip %s' }
]
imv = [
    { run = 'imv %s', orphan = true }
]
imv_animated = [
    { run = 'imv -u linear %s', orphan = true }
]
play-wine = [
    { run = 'export WINE_JOYSTICK_DISABLE_LO_DI=1 && cd "$(dirname "$1")" && wine "$(basename "$1")"', orphan = true, desc = "Run with Wine" }
]
play = [
	{ run = 'vlc %s', orpan = true }
]
pdf = [
	{ run = 'zathura %s', orphan = true }
]
edit = [
	{ run = "nvim %s", block = true },
]

[open]
prepend_rules = [
	{ url = "*.pdf", use = "pdf" },
	{ url = "*.zip", use = "unzip" },
]

[[plugin.prepend_fetchers]]
id    = "git"
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
id    = "git"
url   = "*/"
run   = "git"
group = "git"
