##############################################
############## HYPRLOCK CONFIG ###############
##############################################

general {
  ignore_empty_input = true
}

background {
    path = screenshot 
    color = rgba(0, 0, 0, 0.5)
    blur_passes = 2
    blur_size = 6
}

input-field {
    fade_on_empty = false
    position = 0, -70
    placeholder_text = Input Password
    inner_color = rgb(1a1a1a)
    outline_thickness = 0
    font_color = rgb(ffffff)
    font_family = Google Sans 
    size = 300, 70
}

shape {
  size = 240, 260
  position = 0, 110
  rounding = 30
  color = rgb(1a1a1a)
}

label {
   text = $USER 
   font_family = Google Sans
   position = 0, 10
}

image {
   path = ~/.config/eww/images/profile_picture.png
   position = 0, 135
}

label {
  position = 0, -500
  font_family = Google Sans
  onclick = "playerctl" play-pause
  text = cmd[update:500] ~/.config/hypr/scripts/lock_player_data.sh
}

shape {
  position = 0, 510
  size = 100, 40
  rounding = 7
  color = rgb(1a1a1a)
}

label {
  text = $TIME
  position = 0, 510
  font_family = Google Sans
  color = rgb(fffffff)
}

shape {
  position = 878, 510
  size = 150, 40
  rounding = 7
  color = rgb(1a1a1a)
}

label {
  position = 878, 510
  font_family = Google Sans
  color = rgb(ffffff)
  text = cmd[update:500] ~/.config/hypr/scripts/random_info.sh 
}

# All other files are found in /home/(user)/.config/hypr/scripts/

##############################################
# Made by Zaydaan Sayed 2026
##############################################
